# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 274c7c2efd10e3045d874729c897cda9c8e9b4432270abdf12c7a31683916e5832432a4cc6b81c9e88904f93aee5775399f19f4a4c0f8cc299ca0e0b341a5ac0

test:
  secret_key_base: f388aa264d7cc297ec2e53c5fc4892416f99322d36d1a0b97447a63d342c4e75594dc0141c4d065095f58ffb94ca4c670b17a8debc41522d8ba6b8fd06287380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
